### ISSUE TITLE
Fix shceduled jobs search

### ISSUE THREAD

**Issue by UisemanAraujo** [Hannes221/rq-dashboard-fast#81]
In the file jobs.py, in get_job_registrys, after geting the schedule jobs from the Scheduler, the return array it's cleaned but the values are not copied to job array. So this method will never return the scheduled jobs and they would only be showed in the dashboard after they are finished or failed
![image](https://github.com/Hannes221/rq-dashboard-fast/assets/160764531/197f3202-3801-466a-a1ca-c11a5ff44e51)

**Comment by arnestrickmann** [comment]
@UisemanAraujo Thank you! we're on it.
