### ISSUE TITLE
Job link bug on the Workers tab

### ISSUE THREAD

**Issue by mccauleyp** [Hannes221/rq-dashboard-fast#93]
Hi There, 

Thanks so much for developing this resource--it's super useful! 

I noticed a tiny bug on the `Workers` tab of the dashboard. If you click a job link there for a running job, it directs to the wrong URL, e.g.
```
http://127.0.0.1:8000/rq/jobs/{job-id}
```
And then we get a `{"detail": "Not Found"}` response. 

I think the `jobs` in that URL should swap to `job` instead. 

Cheers!

**Comment by Hannes221** [comment]
Thank you! @mccauleyp. Addressed in https://github.com/Hannes221/rq-dashboard-fast/releases/tag/v0.5.7
