### ISSUE TITLE
Meta dict display on job details page

### ISSUE THREAD

**Issue by mccauleyp** [Hannes221/rq-dashboard-fast#94]
Hi There, 

The recent traceback formatting capability on the job details page is awesome! That looks great. That change seemed to have also had the side effect of altering how the job metadata dict is displayed:

![Screenshot 2024-08-14 at 6 58 31 PM](https://github.com/user-attachments/assets/a8f28f76-b8b2-47b6-b091-607de2745754)

Previously, long dictionaries would wrap onto multiple lines, whereas now it truncates the dict to the screen width. I wonder if it might be preferable to continue wrapping that dict or perhaps formatting it with something like `pprint.pformat`?

Cheers!

**Comment by Hannes221** [comment]
Thank you @mccauleyp! Addressed in https://github.com/Hannes221/rq-dashboard-fast/releases/tag/v0.5.7.

**Comment by mccauleyp** [comment]
> Thank you @mccauleyp! Addressed in https://github.com/Hannes221/rq-dashboard-fast/releases/tag/v0.5.7.

Awesome, thanks for the new release :)
